apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-generador
  namespace: vallegrande
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-generador
  template:
    metadata:
      labels:
        app: springboot-generador
    spec:
      containers:
      - name: springboot-generador
        image:  luistasayco2004/springboot-generador:v2.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"  
            cpu: "500m"     
          limits:
            memory: "512Mi" 
            cpu: "1"       
