apiVersion: v1
kind: Service
metadata:
  name: springboot-generador
  namespace: vallegrande
spec:
  type: LoadBalancer 
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: springboot-generador
